version: 2
updates:
  # @sepruko/monorepo-dotdev
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      timezone: 'Australia/Sydney'
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
    commit-message:
      prefix: 'deps:'
    labels: ['deps', 'needs triage']
    versioning-strategy: 'increase'

  # @sepruko/dotdev
  - package-ecosystem: 'npm'
    directory: '/apps/dotdev/'
    schedule:
      timezone: 'Australia/Sydney'
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
    commit-message:
      prefix: 'deps(dotdev):'
    labels: ['deps', 'needs triage']
    versioning-strategy: 'increase'

  # @sepruko/dict-dotdev
  - package-ecosystem: 'npm'
    directory: '/packages/dict-dotdev/'
    schedule:
      timezone: 'Australia/Sydney'
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
    commit-message:
      prefix: 'deps(dict-dotdev):'
    labels: ['deps', 'needs triage']
    versioning-strategy: 'increase'
